server:
  port: 8081
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: dt-nexus-crm
  datasource:
    url: jdbc:mysql://localhost:3306/dt_nexus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 041817
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true