server:
  port: 8081
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: dt-nexus-crm
  datasource:
    url: jdbc:mysql://localhost:3306/dt_nexus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 041817
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ssk-proj-BkxkpEYUtUCUdVMnRC8_x-A_PV4yCEzPYl9kAddACNML3UKJiSGqiBy6c5zzVZjBks4cLuMSW-T3BlbkFJ0h8X0btICckGyoYLZvCI-ow56-zrB5n1mRxPE1s6nDCyoK--nak_gje5PhFiXkpAkJU6FNJ6gA
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3