ALTER TABLE contacts
    ADD COLUMN IF NOT EXISTS vehicle_model VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS vehicle_plate VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS vehicle_chassis VARCHAR(17) NULL,
    ADD COLUMN IF NOT EXISTS vehicle_km INT NULL,
    ADD COLUMN IF NOT EXISTS inspection_external TEXT NULL,
    ADD COLUMN IF NOT EXISTS inspection_internal VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS fluid_status VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS fuel_level VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS signature_accepted BOOLEAN NULL;
